### ISSUE TITLE
Should we split the repository ?

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#10]
We should split the repository in two ones using http://help.github.com/split-a-subpath-into-a-new-repo/ to maintain version numeration easy.

**Comment by jinroh** [comment]
I agree

**Comment by jinroh** [comment]
Or not, je sais pas si c'est vraiment utile...peut être..tu penses ?

**Comment by alexstrat** [comment]
Ça éviterai aussi de faire des merges dégueus.. meme si la solution était là : http://help.github.com/subtree-merge/

**Comment by alexstrat** [comment]
See issue #15
