### ISSUE TITLE
Making a system of bots to run tests ?

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#23]

**Comment by jinroh** [comment]
Je pensais a ça et je me suis dis que le plus simple ça restait de lancer des clients node. Mais encore faudrait-il que socket.io-client fonctionne sur node ce qui n'a pas l'air d'être le cas...

Tu pensais à d'autres choses ? T'as vu des émulateurs de browser ?

**Comment by alexstrat** [comment]
Je crois, que l'on peut totalement faire marcher `socket.io` en client coté serveur.. Ce qu'il y' a c'est qu'il ne faut pas utiliser le build de `/dist` (duquel les éléments exécuté concernant node sont virés) mais directement `io.js` qu'il ya dans le dossier `/lib` de `socket.io-client`.

Alors c'est vrai qu'on a deux solutions :
1. soit on émule un browser ou des browser avec `zombie.js`
2. soit on émule des nodes directement dans node.js en se basant sur socket.io-client dans node

Avec la solution 2 on quand même plus de controle sur ce qui se passe. Après ça va pas être évident de gérer le fait qu'il faut de manière indépendante executer d'un coté les tests dans un browser et controller d'un autre coté un/des bot(s) coté node, alors que les tests sont basés sur le comportement de ces bots !!

**Comment by alexstrat** [comment]
FOUND
![Bot](http://images3.wikia.nocookie.net/starwars/nl/images/thumb/b/b1/OOM_Command_Battle_Droid.jpg/250px-OOM_Command_Battle_Droid.jpg)
