### ISSUE TITLE
Du coup ? / So, well ?

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#24]
Du coup, on en est où ?

**Comment by jinroh** [comment]
Du coup il faut encore implémenter le iterativeFindNode mais difficile de tester cette fonction sans des bots fonctionnels...

**Comment by alexstrat** [comment]
That's my job fot Today !! Awful rainy day..

**Comment by alexstrat** [comment]
Au final qu'est ce que tu veux qu'il fasse un bon bot ?
