### ISSUE TITLE
Tests in node fail..

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#27]

**Comment by jinroh** [comment]
c'est socket.io  je crois

**Comment by alexstrat** [comment]
C'était ça.. en partie.

Donc j'ai fait un build special node qui enleve socket.io-client. Cependant il est normalement toujours grâce à un require, donc ça devrait marcher dans node quand meme..

Du coup, ça enleve pas mal d'erreur lors du test mais il reste un probleme avec when.js, donc je te laisse gérer..

**Comment by jinroh** [comment]
ok je vais regarder ça mais ca devrait pas trop poser de probleme

**Comment by alexstrat** [comment]
Oui je pense aussi.. Tu pourras checker issue #26 et l'histoire des packet/message.. Ça m'intrige tout ça..

**Comment by jinroh** [comment]
non non  c'est bon, je sais pas si tu as vu mais j'ai commité pour dire que j'avais buggé, j'avais juste pas redémarré mon router ....

**Comment by jinroh** [comment]
j'ai modifié le system de when.js et ça doit bien marcher maintenant !

**Comment by alexstrat** [comment]
indeed
