### ISSUE TITLE
Bootstrap and Bot server

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#29]
RESTFul..

![droid-server](http://www.dk.co.uk/static/html/features/starwars/technology_gallery/images/Battle%20Droid%20Troop%20Carrier.jpg)

**Comment by alexstrat** [comment]
Du coup tu peux me rappeler ce que devrais faire un serveur de bootsatrap ?

**Comment by jinroh** [comment]
Qu'est-ce qu'on fait par rapport à ce sytème de bots. en quoi nous est-il encore utile (c'est une vraie question, je n'ai aucun a priori) ?

**Comment by alexstrat** [comment]
Bah pour l'instant c'est pas utile vu qu'on arrive à se connecter à Mainline, mais peut etre pour plus tard quand on passera en xmpp.. Et encore, rien ne nous empechera de faire un proxy Mainline <> JSON(ou XML)-RPC over XMMP.
