### ISSUE TITLE
Logic Routing Table : ping oldest..

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#32]
Lorsqu'on veut ajouter un nouveau peer et que son KBucket est full et non splittable, on prend le plus vieux peer du KBucket, on le PING et s'il répond on laisse tomber le nouveau. 

Ne penses tu pas qu'on devrait les pinger un par un dans l'ordre décroissant de vieillesse jusqu'à ce qu'il y en ait un qui ne réponde pas ?

C'est déjà vu quelque part ?

**Comment by jinroh** [comment]
Alors là je ne fais que me fier à la spec....

**Comment by alexstrat** [comment]
Oui oui je m'en doutais.. A garder sous le coude donc !
