### ISSUE TITLE
Unable to retrieve value when stored on self?

### ISSUE THREAD

**Issue by garyhodgson** [jinroh/kadoh#64]
Hi,

It seems that a node cannot retrieve a value which is stored within itself.

If I run a simple UDP DHT example with only two nodes, store an arbitrary value, identify the node where it is stored, and then perform a get for that key, I get a "value not found for key" result.

**Comment by alexstrat** [comment]
Yes, indeed that's an edge case that needs to be treated at application level (in node.js). I corrected it in f87d6b57bf7ee9c354478d3f9d8dde126486f483

Thanks !
