### ISSUE TITLE
SHA1 library for Javascript

### ISSUE THREAD

**Issue by jinroh** [jinroh/kadoh#7]
Find a good SHA1 library for javascript

**Comment by alexstrat** [comment]
So what ?

**Comment by jinroh** [comment]
Ben j'ai mis du temps à trouver un truc qui paraissait vraiment potable et puis je suis tomber sur des librairies maintenues par google alors je me suis dis que c'était pas mal : crypto-js que ça s'appelle.

Le fichier est déjà minifier, ce qui n'est pas forcément cool mais bon...

**Comment by alexstrat** [comment]
Si tu peux trouver les sources (http://code.google.com/p/crypto-js/downloads/detail?name=Crypto-JS%20v2.5.1.zip&can=2&q=) et prendre seulement les algos dont on a besoin (on a pas de besoin de AES etc. ?) en mode decompiler : sha1/sha1.js ou sha256/sha256.js. Attention parce que dans SHA on a quand même besoin du package crypto/crypto.js

**Comment by alexstrat** [comment]
Du coup on a le controle sur le namespace

**Comment by jinroh** [comment]
Ouai c'est ce que j'avais vu. Je vais intégrer les deux fichiers en un si tu veux

**Comment by jinroh** [comment]
Done
