### ISSUE TITLE
Organize as Classes

### ISSUE THREAD

**Issue by alexstrat** [jinroh/kadoh#9]
Organize client side code as Classes with appropriate namespaces..

Find the appropriate framework that works both on client side and Node (for testing and benchmarking).
# avoidusingcomplexdesignpatternsinwhichweneverknowwhatisThis

**Comment by alexstrat** [comment]
mis ce qu'il  faut, je vais adapter le code pour te montrer

**Comment by alexstrat** [comment]
A part/module of KadOH shoul be declared like that :

``` js
(function(exports){
  var KadOH = exports;
//Dependencies
  var Class = KadOH.core.Class;

  KadOH.sub = {};
  KadOH.sub.module = Class({
    initialize : function() { .....},

    method1 : function(){ ......}

   });


})('object' === typeof module ? module.exports : (this.KadOH = {}));
```

See https://github.com/ded/klass

**Comment by jinroh** [comment]
C'est tout on il faudra rajouter des trucs pour le testing à la mode de socket-io.client ?

**Comment by alexstrat** [comment]
Je sais pas encore..

**Comment by jinroh** [comment]
Je l'implemente comme ca pour l'instant dans les fonctions déjà faites ou tu es peut être entrain de la faire ?

**Comment by alexstrat** [comment]
Non vas y !

**Comment by alexstrat** [comment]
Pffff.. Attends 2 sec, je pond un truc et tu me dis ce que tu en penses...

**Comment by jinroh** [comment]
Ah merde ... j'avais pas vu ... (!!)

**Comment by alexstrat** [comment]
Pas grave, j'ai besoin de réfléchir de toute manière et de ton avis en plus donc bon.. Je vais me chercher un macho je reviens ! ;)
